### ISSUE TITLE
android 6 的 su 参数格式不一样  Android 6 has different su usage

### ISSUE THREAD

**Issue by RonaldinhoL** [wrlu/FridaHooker#2]
在 6.0 的镜像中测试，无法直接启动 frida-server

usage: su [UID[,GID[,GID2]...]] [COMMAND [ARG...]]

**Comment by wrlu** [comment]
su命令的使用方法不是依赖于Android版本（因为su并非Android官方的二进制）而是依赖于su二进制的版本自身。
或许你正在使用旧版本的su二进制，例如旧版本的SuperSU
我们需要在程序中做更多的工作才能识别su二进制的版本，所以当前我们高度推荐您使用Magisk来获得root访问而不是SuperSU。我已经在Nexus 5, 带有Magisk的Android 6.0.1上测试了应用并且可以正常工作。如果你有更多问题欢迎继续提出issue ：）

The su command usage is NOT depending on the Android version (for su is not an Android official binary) but the su binary version itself.
Maybe you are using a old su binary, for example the old version of SuperSU.
We need do more work to recognize the su binary version in our program. so we highly recommend use Magisk instead of SuperSU to get root access now. We have tested the App on my Nexus 5, Android 6.0.1 with Magisk and it works good. If you have any further question, issue is welcome. :)

**Comment by RonaldinhoL** [comment]
soga.
